# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NFT Buzz Today
email: contact@nftbuzztoday.com
description: Get Latest Updates on NFT & Cryptocurrency daily
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://blog.nftbuzztoday.com" # The base hostname & protocol for your site
github_username: nftbuzztoday
twitter_username: nftbuzztoday

markdown: kramdown
permalink: pretty
paginate: 12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

plugins: [jekyll-paginate]
# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Robert:
    name: Robert Alexandra
    bio: Author of NFT Buzz today, He is expert in understanding NFT markets and have deep knowledge on Cryptocurrency
    gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email: contact@nftbuzztoday.com
    website: http://nftbuzztoday.com
    twitter_username: nftbuzztoday
    
    gems: - jekyll-sitemap
